# Solve a System of Equations with Python, using `numpy`
Here, we are using the `numpy` Python package.

It simplifies things quite a bit ;)

In [5]:
import numpy as np
import datetime
#
# Here we use the 'numpy' Python library
# Is simplifies the process quite a bit ;)
#
# See https://www.tutorialspoint.com/numpy/
# For special characters and symbols, see https://pythonforundergradengineers.com/unicode-characters-in-python.html
#
matrix = np.array([
    [12, 13, 14],
    [1.345, -654, 0.001],
    [23.09, 5.3, -12.34]
])

print("System coefficients: {}".format(matrix))

constants = np.array([234, 98.87, 9.876])
print("System constants {}".format(constants))

before = datetime.datetime.now()
solution = np.linalg.solve(matrix, constants)
after = datetime.datetime.now()
print("Done in {}s and {}\u03BCs (=> {}\u03BCs)".format((after - before).seconds, 
                                                          (after - before).microseconds,
                                            (((after - before).seconds * 1000000) + (after - before).microseconds)))
print("By 'solve': {}".format(solution))

before = datetime.datetime.now()
# Resolution
inverse = np.linalg.inv(matrix)
print('Inverse: {}'.format(inverse))
solution_2 = np.dot(inverse, constants)
after = datetime.datetime.now()
print("Done in {}s, {}\u03BCs (=> {}\u03BCs)".format((after - before).seconds, (after - before).microseconds,
                                            (((after - before).seconds * 1000000) + (after - before).microseconds)))
print("By 'dot product': {}".format(solution_2))


System coefficients: [[ 1.200e+01  1.300e+01  1.400e+01]
 [ 1.345e+00 -6.540e+02  1.000e-03]
 [ 2.309e+01  5.300e+00 -1.234e+01]]
System constants [234.     98.87    9.876]
Done in 0s and 151μs (=> 151μs)
By 'solve': [ 6.48822195 -0.13781661 11.28092518]
Inverse: [[ 2.61538652e-02  7.60340789e-04  2.96721940e-02]
 [ 5.38622472e-05 -1.52748712e-03  6.09841146e-05]
 [ 4.89609577e-02  7.66660219e-04 -2.54899372e-02]]
Done in 0s, 1531μs (=> 1531μs)
By 'dot product': [ 6.48822195 -0.13781661 11.28092518]
