## MNIST Data Set (Modified National Institute of Standards and Technology)

In [4]:
from keras.datasets import mnist

In [34]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print("Train Images shape: {}, {}".format(train_images.shape, train_images.dtype))
print("{} train labels".format(len(train_labels)))
print("Train labels: {}".format(train_labels))

Train Images shape: (60000, 28, 28), uint8
60000 train labels
Train labels: [5 0 4 ... 5 6 8]


In [35]:
print("Test Iages shape: {}, {}".format(test_images.shape, test_images.dtype))
print("{} test labels".format(len(test_labels)))
print("Test labels: {}".format(test_labels))

Test Iages shape: (10000, 28, 28), uint8
10000 test labels
Test labels: [7 2 1 ... 4 5 6]


### Network Architecture

In [36]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [37]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [38]:
network.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_6 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


### Now, we reshape the data
- Images are `(28 * 28, uint8)`, we need `(28 * 28, float32)`
- Images' pixels are in `[0, 255]`, we need them in `[0, 1]`

In [39]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255


In [40]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

### A look at the new shapes

In [41]:
print("Train Images shape: {}, {}".format(train_images.shape, train_images.dtype))
print("{} train labels".format(len(train_labels)))
print("Train labels: {}".format(train_labels))

print("Test Iages shape: {}, {}".format(test_images.shape, test_images.dtype))
print("{} test labels".format(len(test_labels)))
print("Test labels: {}".format(test_labels))

Train Images shape: (60000, 784), float32
60000 train labels
Train labels: [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
Test Iages shape: (10000, 784), float32
10000 test labels
Test labels: [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### Now we train the model for real

In [42]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 5s 77us/step - loss: 0.2579 - acc: 0.9245
Epoch 2/5
60000/60000 [==============================] - 4s 70us/step - loss: 0.1039 - acc: 0.9690
Epoch 3/5
60000/60000 [==============================] - 4s 70us/step - loss: 0.0686 - acc: 0.9796
Epoch 4/5
60000/60000 [==============================] - 4s 70us/step - loss: 0.0503 - acc: 0.9848
Epoch 5/5
60000/60000 [==============================] - 4s 71us/step - loss: 0.0382 - acc: 0.9887


### Get an idea of how good the model is
Using the _test_ data

In [29]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print("Test Accuracy: {}".format(test_acc))

10000/10000 [==============================] - 0s 50us/step
Test Accuracy: 0.9807
